###
GET http://127.0.0.1:5000/api/v1/dictionary/all-methods HTTP/1.1
content-type: application/json
locale: pl

###
GET http://127.0.0.1:5000/api/v1/descriptions/home HTTP/1.1
content-type: application/json
locale: en


###
POST http://127.0.0.1:5000/api/v1/results HTTP/1.1
content-type: application/json

{
    "matrix": [
        [1, 2, 3],
        [1, 2, 3]
    ],
    "extensions": ["fuzzy"],
    "types": [],
    "method": [],
    "methodCorrelations": [],
    "methodRankings": [],
    "rankingCorrelations": []
}


###
GET http://api.make-decision.it/api/v1/descriptions/methods HTTP/1.1
content-type: application/json
locale: en